# Generated by Django 3.0.3 on 2020-02-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatree', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='l_name',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
