# Generated by Django 3.0.3 on 2020-02-17 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datatree', '0002_auto_20200217_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datatree.People'),
        ),
    ]
